version: '3.8'
services:
  mongodb:
    image: 'mongo'
    volumes:
      - multi-vol:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: mongoadmin
#      MONGO_INITDB_ROOT_PASSWORD: secret
    env_file:
      - ./env/.mongo.env
  backend:
    #    build:
    #      context: ./backend
    #      dockerfile: Dockerfile
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/.backend.env
    ports:
      - '80:80'
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - backend
volumes:
  multi-vol:
